### ISSUE TITLE
Allow disabling the test pod

### ISSUE THREAD

**Issue by karldreher** [kellnr/helm#4]
https://github.com/kellnr/helm/tree/2eacb1acc2a92cdce1e25653b6c09f645a48f4de/charts/kellnr/templates/tests

When templating this chart using `helm template kellnr kellnr/kellnr --values values.yaml`, as-written, the pod spec in kellnr/templates/tests is rendered.  While it's mostly innocuous, it would be nice to be able to remove the pod if it is decided by the chart consumer not to be necessary.  There would be several scenarios where it may be advantageous to remove it. 

I suggest that this is a top-level toggle within the values, e.g.
```yaml
testPod: false # Default is false
```

**Comment by secana** [comment]
Thanks for the issue. Honestly, I had no idea the test pod is still in the template. I'll throw it out.

**Comment by karldreher** [comment]
Cool, thanks!
