### ISSUE TITLE
Example about TLS and ingress.annotations

### ISSUE THREAD

**Issue by vittoriomonaco** [kellnr/helm#7]
Hello,

I wanted to ask if it would be possible to clarify some details regarding the TLS configuration and the ingress.annotations section.

For detail, I am providing the command successfully executed on my infrastructure.

Environment:
- K3S
- Ingress: Traefik
- cert-manager, for certificate generation
- external-dns, for DNS record generation and configuration on PowerDNS (external DNS to Kubernetes)

```sh
helm install kellnr kellnr/kellnr --namespace kellnr-private-registry \
  --set pvc.enabled=true \
  --set pvc.storageClassName=ceph-rbd-sc \
  --set pvc.storage=10Gi \
  --set kellnr.origin.hostname="kellnr.example.com" \
  --set kellnr.origin.port=443 \
  --set kellnr.origin.protocol=https \
  --set kellnr.apiProtocol=https \
  --set certificate.enabled=true \
  --set certificate.issuerRef.name="letsencrypt-production" \
  --set ingress.className=traefik \
  --set ingress.tls.enabled=true \
  --set ingress.tls.certSource=secret \
  --set ingress.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="kellnr.example.com"
```

**TLS**:
 - It is not clear that it is necessary to use kellnr.origin.port and kellnr.origin.protocol
 - kellnr.apiProtocol is not present in values.yaml, creating confusion about its usage
 - Should ingress.tls.enabled and ingress.tls.certSource be used?

**ingress.annotations**:
From what is stated in the documentation, I thought it should be treated like the other parameters, but it is correctly interpreted with the escape \ and in the indicated format.

Could you provide some examples on how to use ingress.annotations, even in the case where more than one annotation needs to be used?

Thank you very much for the work done.

**Comment by jacobsvante** [comment]
This worked for me when using Traefik:

```bash
helm template \
  --include-crds \
  --namespace kellnr \
  --set pvc.enabled=true \
  --set pvc.storageClassName="my-storage-class" \
  --set pvc.storage="5Gi" \
  --set kellnr.origin.hostname="kellnr.example.com" \
  --set kellnr.origin.port=443 \
  --set kellnr.origin.protocol=https \
  --set kellnr.docs.enabled=true \
  --set kellnr.registry.authRequired=true \
  --set resources.limits.cpu=100m \
  --set resources.limits.memory=128Mi \
  --set resources.requests.cpu=100m \
  --set resources.requests.memory=128Mi \
  --set certificate.enabled=true \
  --set certificate.issuerRef.name=letsencrypt-prod \
  --set-json ingress.annotations='{"traefik.ingress.kubernetes.io/router.entrypoints":"websecure"}' \
  --set-json service.annotations='{"traefik.ingress.kubernetes.io/service.nativelb":true}' \
  --set service.api.port=8080 \
  --set kellnr.local.port=8080 \
  kellnr \
  kellnr/kellnr \
  > ~/Downloads/kellnr.yaml
```

**Comment by secana** [comment]
Thanks for providing the example!
